package com.vendsy.bartsy.model;

import org.json.JSONException;
import org.json.JSONObject;

import com.j256.ormlite.field.DatabaseField;
import com.vendsy.bartsy.R;

/**
 * @author Seenu
 * 
 *         A MenuDrink object we are creating.
 */
public class Item {
	// id is generated by the database and set on the object automatically
	private String itemId;
	private String title;
	private String image;
	private String description;
	private float price;
	private String specialPrice;
	private String venueId;
	public String valid = null;

	private Section section;
	
	public Item () {
	}
	
	public Item(String title, String description, float price) {
		this.title = title;
		this.description = description;
		this.price = price;
	}
	
	public Item(JSONObject object) {
		try {
			if (object.has("name"))
				this.title = object.getString("name");
			if (object.has("itemName"))
				this.title = object.getString("itemName");

			if (object.has("description"))
				this.description = object.getString("description");

			if (object.has("price"))
				this.price = Float.parseFloat(object.getString("price"));
			if (object.has("basePrice"))
				this.price = Float.parseFloat(object.getString("basePrice"));

			if (object.has("id"))
				this.itemId = object.getString("id");
			if (object.has("itemId"))
				this.itemId = object.getString("itemId");
			
			valid = "yes";

		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

		// For now always use the same image for the drink
		this.image = Integer.toString(R.drawable.drinks);

	}


	public String getItemId() {
		return itemId;
	}

	public void setItemId(String drinkId) {
		this.itemId = drinkId;
	}

	
	/**
	 * @return the venueId
	 */
	public String getVenueId() {
		return venueId;
	}

	/**
	 * @param venueId the venueId to set
	 */
	public void setVenueId(String venueId) {
		this.venueId = venueId;
	}

	/**
	 * @return the title
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * @param title
	 *            the title to set
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * @return the image
	 */
	public String getImage() {
		return image;
	}

	/**
	 * @param image
	 *            the image to set
	 */
	public void setImage(String image) {
		this.image = image;
	}

	/**
	 * @return the description
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * @param description
	 *            the description to set
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * @return float the price
	 */
	public float getPrice() {
		return price;
	}

	/**
	 * @param price
	 *            the price to set
	 */
	public void setPrice(float price) {
		this.price = price;
	}

	/**
	 * @return the price_special
	 */
	public String getPrice_special() {
		return specialPrice;
	}

	/**
	 * @param price_special
	 *            the price_special to set
	 */
	public void setPrice_special(String price_special) {
		this.specialPrice = price_special;
	}

	/**
	 * @return the section
	 */
	public Section getSection() {
		return section;
	}

	/**
	 * @param section
	 *            the section to set
	 */
	public void setSection(Section section) {
		this.section = section;
	}

}
