package com.vendsy.bartsy.model;

import org.json.JSONException;
import org.json.JSONObject;

import com.j256.ormlite.field.DatabaseField;
import com.vendsy.bartsy.R;

/**
 * @author Seenu
 * 
 *         A MenuDrink object we are creating.
 */
public class MenuDrink {
	// id is generated by the database and set on the object automatically
	private String drinkId;
	private String title;
	private String image;
	private String description;
	private float price;
	private String price_special;
	private String venueId;
	public String valid = null;

	private Section section;
	

	public MenuDrink() {
		// TODO Auto-generated constructor stub
	}

	public String getDrinkId() {
		return drinkId;
	}

	public void setDrinkId(String drinkId) {
		this.drinkId = drinkId;
	}
	
	public MenuDrink(JSONObject object) {
		// TODO Auto-generated constructor stub

		try {
			if (object.has("name")) {
				this.title = object.getString("name");

			}
			if (object.has("description")) {
				this.description = object.getString("description");
			}
			if (object.has("price")) {
				try {
					this.price = Float.parseFloat(object.getString("price"));
				} catch (NumberFormatException e) {
				}
			}
			if (object.has("id")) {
				this.drinkId = object.getString("id");
			}
			
			valid = "yes";

		} catch (JSONException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

		// For now always use the same image for the drink
		this.image = Integer.toString(R.drawable.drinks);

	}

	/**
	 * @return the venueId
	 */
	public String getVenueId() {
		return venueId;
	}

	/**
	 * @param venueId the venueId to set
	 */
	public void setVenueId(String venueId) {
		this.venueId = venueId;
	}

	/**
	 * @return the title
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * @param title
	 *            the title to set
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * @return the image
	 */
	public String getImage() {
		return image;
	}

	/**
	 * @param image
	 *            the image to set
	 */
	public void setImage(String image) {
		this.image = image;
	}

	/**
	 * @return the description
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * @param description
	 *            the description to set
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * @return float the price
	 */
	public float getPrice() {
		return price;
	}

	/**
	 * @param price
	 *            the price to set
	 */
	public void setPrice(float price) {
		this.price = price;
	}

	/**
	 * @return the price_special
	 */
	public String getPrice_special() {
		return price_special;
	}

	/**
	 * @param price_special
	 *            the price_special to set
	 */
	public void setPrice_special(String price_special) {
		this.price_special = price_special;
	}

	/**
	 * @return the section
	 */
	public Section getSection() {
		return section;
	}

	/**
	 * @param section
	 *            the section to set
	 */
	public void setSection(Section section) {
		this.section = section;
	}

}
