package com.vendsy.bartsy.model;

import org.json.JSONException;
import org.json.JSONObject;

/**
 * 
 * @author Seenu Malireddy
 *
 */

public class Notification {
	
	public static final String TYPE_CHECKIN = "checkin";
	public static final String TYPE_CHECKOUT = "checkout";
	public static final String TYPE_PLACE_ORDER = "placeOrder";
	public static final String TYPE_UPDATE_ORDER = "updateorder";
	public static final String TYPE_OFFER_DRINK = "offer";

	private String id; // unique id generated by the server
	private String message;
	private String type;
	private String userImage;
	private String createdTime;
	
	@Override
	public String toString() {

		return  "{" +
				" id: " + id +
				" message: " + message +
				" type: " + type +
				" userImage: " + userImage + 
				" createdTime: " + createdTime +
				"}";
	}
	
	public Notification(JSONObject json) {
		try {
			message = json.getString("message");
			type = json.getString("type");
			createdTime = json.getString("createdTime");
		} catch (JSONException e) {
		}
	}

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getMessage() {
		return message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getUserImage() {
		return userImage;
	}

	public void setUserImage(String userImage) {
		this.userImage = userImage;
	}

	public String getCreatedTime() {
		return createdTime;
	}

	public void setCreatedTime(String createdTime) {
		this.createdTime = createdTime;
	}
	
}
