package com.vendsy.bartsy.model;

import java.util.ArrayList;
import java.util.List;

import com.j256.ormlite.field.DatabaseField;

/**
 * @author Seenu
 * 
 *         A Section object we are creating and persisting to the database.
 */
public class Section {
	// id is generated by the database and set on the object automatically
	@DatabaseField(generatedId = true)
	private int id;
	@DatabaseField
	private String name;
	@DatabaseField
	private String venueId;

	// data will not save in db
	private List<Item> drinks = new ArrayList<Item>();

	public List<Item> getDrinks() {
		return drinks;
	}

	public void setDrinks(List<Item> drinks) {
		this.drinks = drinks;
	}

	public Section() {
		// TODO Auto-generated constructor stub
	}

	/**
	 * @return the venueId
	 */
	public String getVenueId() {
		return venueId;
	}

	/**
	 * @param venueId the venueId to set
	 */
	public void setVenueId(String venueId) {
		this.venueId = venueId;
	}

	/**
	 * @return the id
	 */
	public int getId() {
		return id;
	}

	/**
	 * @param id
	 *            the id to set
	 */
	public void setId(int id) {
		this.id = id;
	}

	/**
	 * @return the name
	 */
	public String getName() {
		return name;
	}

	/**
	 * @param name
	 *            the name to set
	 */
	public void setName(String name) {
		this.name = name;
	}

}
