package com.vendsy.bartsy.model;

import org.json.JSONException;
import org.json.JSONObject;

import android.util.Log;

import com.vendsy.bartsy.utils.Constants;
import com.vendsy.bartsy.utils.WebServices;

public class Venue {
	
	public static final String TAG = "Venue";

	public static final String Shared_Pref_KEY = "AllVenues";

	private String id; // unique id generated by the server
	private String name;
	private String latitude;
	private String longitude;
	private String address;
	private String payPalId;
	private int    userCount;
	private String wifiName;
	private String wifiPassword;
	private String wifiTypeOfAuthentication;
	private String wifiNetworkType;
	private String status;
	private int	   orderTimeout;
	private double  taxRate;
	private String imagePath = null;

	
	/**
	 * TODO - Constructors / parsers
	 */
	
	public Venue (JSONObject json) {
		
		try {
			setId(json.getString("venueId"));
			setName(json.getString("venueName"));
			
			if (json.has("latitude"))
				setLatitude(json.getString("latitude"));
			if (json.has("longitude"))
				setLongitude(json.getString("longitude"));
			if (json.has("address"))
				setAddress(json.getString("address"));
			if (json.has("checkedInUsers"))
				setUserCount(json.getInt("checkedInUsers"));
			if (json.has("cancelOrderTime"))
				setOrderTimeout(json.getInt("cancelOrderTime"));
			
			if (json.has("wifiPresent") && json.getInt("wifiPresent") != 0) {
				setWifiName(json.getString("wifiName"));
				setWifiPassword(json.getString("wifiPassword"));
				SetWifiTypeOfAuthentication(json.getString("typeOfAuthentication"));
			}
			if (json.has("venueStatus"))
				setStatus(json.getString("venueStatus"));
		
			if (json.has("totalTaxRate"))
				taxRate = Double.parseDouble(json.getString("totalTaxRate"));
			else
				taxRate = Constants.taxRate;
		
			if (json.has("orderTimeout"))
				setOrderTimeout(json.getInt("orderTimeout"));
			
			if (json.has("venueImagePath"))
				setImagePath(WebServices.DOMAIN_NAME + json.getString("venueImagePath"));
			
			if(json.has("wifiNetworkType"))
				wifiNetworkType = json.getString("wifiNetworkType");
			
		} catch (JSONException e) {
			e.printStackTrace();
		}
	}
	
	
	/**
	 * TODO - Serializers
	 */
	
	@Override
	public String toString() {

		JSONObject json = new JSONObject();
		
		try {
			if (id != null)
				json.put("venueId", id);
			if (name != null)
				json.put("venueName", name);
			if (latitude != null)
				json.put("latitude", latitude);
			if (longitude != null)
				json.put("longitude", longitude);
			
			json.put("checkedInUsers", userCount);
			json.put("cancelOrderTime", orderTimeout);
			
			if (wifiName != null && wifiPassword != null && wifiTypeOfAuthentication != null) {
				json.put("wifiPresent", 1);
				json.put("wifiName", wifiName);
				json.put("wifiPassword", wifiPassword);
				json.put("typeOfAuthentication", wifiTypeOfAuthentication);
			}

			if (status != null)
				json.put("venueStatus", status);
			json.put("totalTaxRate", taxRate);
			json.put("orderTimeout", orderTimeout);

		} catch (JSONException e) {
			e.printStackTrace();
		}
		
		return json.toString();
	}
	
	
	/**
	 * 
	 * TODO Getters and setters
	 * 
	 */

	public String getStatus() {
		return status;
	}
	
	public void setStatus(String status) {
		this.status = status;
	}

	public String getWifiName() {
		return wifiName;
	}
	
	public void setWifiName(String wifiName) {
		this.wifiName = wifiName;
	}
	
	public String getWifiPassword() {
		return wifiPassword;
	}
	
	public void setWifiPassword(String wifiPassword) {
		this.wifiPassword = wifiPassword;
	}
	
	public String getWifiTypeOfAuthentication() {
		return wifiTypeOfAuthentication;
	}
	
	public void SetWifiTypeOfAuthentication(String wifiTypeOfAuthentication) {
		this.wifiTypeOfAuthentication = wifiTypeOfAuthentication;
	}
	
	public int getUserCount() {
		return userCount;
	}

	public void setUserCount(int userCount) {
		this.userCount = userCount;
	}
	
	public String getAddress() {
		return address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public boolean hasLatLong() {
		return !latitude.equals("") && latitude != null && !longitude.equals("") && longitude != null;
	}
	
	public boolean hasWifi() {
		return wifiName!=null;
	}
	
	public String getLatitude() {
		return latitude;
	}

	public void setLatitude(String latitude) {
		this.latitude = latitude;
	}

	public String getLongitude() {
		return longitude;
	}

	public void setLongitude(String longitude) {
		this.longitude = longitude;
	}

	public String getPayPalId() {
		return payPalId;
	}

	public void setPayPalId(String payPalId) {
		this.payPalId = payPalId;
	}

	public int getOrderTimeout() {
		return orderTimeout;
	}
	
	public void setOrderTimeout(int orderTimeout) {
		this.orderTimeout = orderTimeout;
	}

	public double getTaxRate() {
		
		if (taxRate == 0) {
			Log.e(TAG, "Missing tax rate");
			return Constants.taxRate / (double) 100;
		} else 
			return taxRate / (double) 100;
	}

	public void setTaxRate(double taxRate) {
		this.taxRate = taxRate;
	}

	public boolean hasImagePath() {
		return imagePath != null;
	}
	
	public String getImagePath() {
		return imagePath;
	}

	public void setImagePath(String imagePath) {
		this.imagePath = imagePath;
	}

	public String getWifiNetworkType() {
		return wifiNetworkType;
	}

	public void setWifiNetworkType(String wifiNetworkType) {
		this.wifiNetworkType = wifiNetworkType;
	}

	public void setWifiTypeOfAuthentication(String wifiTypeOfAuthentication) {
		this.wifiTypeOfAuthentication = wifiTypeOfAuthentication;
	}
	
}
