package com.vendsy.bartsy.model;

public class Venue {

	private String id; // unique id generated by the server
	private String name;
	private String latitude;
	private String longitude;
	private String address;
	private String payPalId;
	private int    userCount;
	private String wifiName;
	private String wifiPassword;
	private String wifiTypeOfAuthentication;
	private String status;
	private int	   orderTimeout;

	@Override
	public String toString() {

		return "{" +
				"id: " + id +
				" name: " + name +
				" userCount: " + userCount +
				" orderTimeout: " + orderTimeout + 
				" latitude: " + latitude +
				" longitude: " + longitude +
				" address: " + address +
				" payPalId: " + payPalId +
				"}";
		
	}
	
	public String getStatus() {
		return status;
	}
	
	public void setStatus(String status) {
		this.status = status;
	}

	public String getWifiName() {
		return wifiName;
	}
	
	public void setWifiName(String wifiName) {
		this.wifiName = wifiName;
	}
	
	public String getWifiPassword() {
		return wifiPassword;
	}
	
	public void setWifiPassword(String wifiPassword) {
		this.wifiPassword = wifiPassword;
	}
	
	public String getWifiTypeOfAuthentication() {
		return wifiTypeOfAuthentication;
	}
	
	public void SetWifiTypeOfAuthentication(String wifiTypeOfAuthentication) {
		this.wifiTypeOfAuthentication = wifiTypeOfAuthentication;
	}
	
	public int getUserCount() {
		return userCount;
	}

	public void setUserCount(int userCount) {
		this.userCount = userCount;
	}
	
	public String getAddress() {
		return address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getLatitude() {
		return latitude;
	}

	public void setLatitude(String latitude) {
		this.latitude = latitude;
	}

	public String getLongitude() {
		return longitude;
	}

	public void setLongitude(String longitude) {
		this.longitude = longitude;
	}

	public String getPayPalId() {
		return payPalId;
	}

	public void setPayPalId(String payPalId) {
		this.payPalId = payPalId;
	}

	public int getOrderTimeout() {
		return orderTimeout;
	}
	
	public void setOrderTimeout(int orderTimeout) {
		this.orderTimeout = orderTimeout;
	}
	
}
