package com.vendsy.bartsy.model;

public class Venue {

	private String id; // unique id generated by the server
	private String name;
	private String latitude;
	private String longitude;
	private String address;
	private String payPalId;
	private int orderCount;
	private int userCount;

	@Override
	public String toString() {

		return "{" +
				"id: " + id +
				" name: " + name +
				" orderCount: " + orderCount +
				" userCount: " + userCount +
				" latitude: " + latitude +
				" longitude: " + longitude +
				" address: " + address +
				" payPalId: " + payPalId +
				"}";
		
	}
	
	public int getOrderCount() {
		return orderCount;
	}

	public void setOrderCount(int orderCount) {
		this.orderCount = orderCount;
	}
	
	public int getUserCount() {
		return userCount;
	}

	public void setUserCount(int userCount) {
		this.userCount = userCount;
	}
	
	public String getAddress() {
		return address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getLatitude() {
		return latitude;
	}

	public void setLatitude(String latitude) {
		this.latitude = latitude;
	}

	public String getLongitude() {
		return longitude;
	}

	public void setLongitude(String longitude) {
		this.longitude = longitude;
	}

	public String getPayPalId() {
		return payPalId;
	}

	public void setPayPalId(String payPalId) {
		this.payPalId = payPalId;
	}

}
