package com.kellislabs.bartsy.model;

import java.util.ArrayList;
import java.util.List;

import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

import com.j256.ormlite.field.DatabaseField;

/**
 * @author Seenu
 * 
 *         A Section object we are creating and persisting to the database.
 */
public class Section {
	// id is generated by the database and set on the object automatically
	@DatabaseField(generatedId = true)
	private int id;
	@DatabaseField
	private String name;

	// data will not save in db
	private List<MenuDrink> drinks = new ArrayList<MenuDrink>();

	public List<MenuDrink> getDrinks() {
		return drinks;
	}

	public void setDrinks(List<MenuDrink> drinks) {
		this.drinks = drinks;
	}

	public Section() {
		// TODO Auto-generated constructor stub
	}

	public Section(JSONObject object) {
		// TODO Auto-generated constructor stub

		try {
			this.name = object.getString("section_name");

			if (object.has("subsections")) {
				JSONArray subsections = object.getJSONArray("subsections");

				if (subsections != null && subsections.length() > 0) {

					JSONObject subSection = subsections.getJSONObject(0);
					if (subSection.has("contents")) {

						JSONArray contents = subSection
								.getJSONArray("contents");
						for (int i = 0; i < contents.length(); i++)

						{
							MenuDrink menuDrink = new MenuDrink(
									contents.getJSONObject(i));
							menuDrink.setSection(this);
							drinks.add(menuDrink);

						}

					}

				}

			}

		} catch (JSONException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

	/**
	 * @return the id
	 */
	public int getId() {
		return id;
	}

	/**
	 * @param id
	 *            the id to set
	 */
	public void setId(int id) {
		this.id = id;
	}

	/**
	 * @return the name
	 */
	public String getName() {
		return name;
	}

	/**
	 * @param name
	 *            the name to set
	 */
	public void setName(String name) {
		this.name = name;
	}

}
