package com.kellislabs.bartsy.model;

import com.j256.ormlite.field.DatabaseField;

/**
 * @author Seenu
 * 
 * A Section object we are creating and persisting to the database.
 */
public class Section {
	// id is generated by the database and set on the object automatically
	@DatabaseField(generatedId = true)
	private int id;
	@DatabaseField
	private String name;
	/**
	 * @return the id
	 */
	public int getId() {
		return id;
	}
	/**
	 * @param id the id to set
	 */
	public void setId(int id) {
		this.id = id;
	}
	/**
	 * @return the name
	 */
	public String getName() {
		return name;
	}
	/**
	 * @param name the name to set
	 */
	public void setName(String name) {
		this.name = name;
	}	
	
	
}
